# Start from the official Node.js LTS image
FROM node:lts-alpine

# Set build-time environment variables
ARG AUTH_AUTHORITY=https://keyloak:8080/auth/realms/master
ARG AUTH_CLIENT_ID=client_id

# Set environment variables
ENV AUTH_AUTHORITY=$AUTH_AUTHORITY
ENV AUTH_CLIENT_ID=$AUTH_CLIENT_ID

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Build the Remix application
RUN npm run build

# Expose port 3001 to the outside world
EXPOSE 3001
EXPOSE 24678

# Command to run the application
CMD ["npm", "run", "dev"]
