services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - KRATOS_PUBLIC_URL=${KRATOS_PUBLIC_URL}
      - KETO_WRITE_URL=${KETO_WRITE_URL}
      - KETO_READ_URL=${KETO_READ_URL}
    ports:
      - "${PORT}:${PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_KRATOS_PUBLIC_URL=${KRATOS_PUBLIC_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  postgres:
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  ksun:
    ports:
      - "4435:4435"

  kratos:
    environment:
      - DSN=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/ory?sslmode=disable&max_conns=20&max_idle_conns=4
      - SERVE_PUBLIC_CORS_ENABLED=true
      # - SERVE_PUBLIC_CROS_ALLOWED_ORIGINS_0=http://localhost:3000
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=${SELFSERVICE_DEFAULT_BROWSER_RETURN_URL}
      - SELFSERVICE_FLOWS_ERROR_UI_URL=${SELFSERVICE_FLOWS_ERROR_UI_URL}
      - SELFSERVICE_FLOWS_SETTINGS_UI_URL=${SELFSERVICE_FLOWS_SETTINGS_UI_URL}
      - SELFSERVICE_FLOWS_RECOVERY_UI_URL=${SELFSERVICE_FLOWS_RECOVERY_UI_URL}
      - SELFSERVICE_FLOWS_LOGIN_UI_URL=${SELFSERVICE_FLOWS_LOGIN_UI_URL}
      - SELFSERVICE_FLOWS_REGISTRATION_UI_URL=${SELFSERVICE_FLOWS_REGISTRATION_UI_URL}
      - SELFSERVICE_FLOWS_VERIFICATION_UI_URL=${SELFSERVICE_FLOWS_VERIFICATION_UI_URL}
      - SELFSERVICE_FLOWS_LOGOUT_DEFAULT_BROWSER_RETURN_URL=${SELFSERVICE_DEFAULT_BROWSER_RETURN_URL}
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin

  keto:
    environment:
      - DSN=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/ory?sslmode=disable
    ports:
      - "4466:4466"
      - "4467:4467"

  mailslurper:
    ports:
      - "4436:4436"
      - "4437:4437"

  typesense:
    ports:
      - "8108:8108"
