services:
  postgres:
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  supertokens:
    ports:
      - "3567:3567"
    environment:
      - POSTGRESQL_HOST=${DB_HOST}
      - POSTGRESQL_PORT=${DB_PORT}
      - POSTGRES_USER=supertokens
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE_NAME=supertokens

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - GO_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    ports:
      - "80:80"

  typesense:
    ports:
      - "8108:8108"

  mailhog:
    ports:
      - "1025:1025"
      - "8025:8025"
