events{}

http {
    include mime.types;

    server {
        listen 80;
        root /usr/share/nginx/html;

        # gzip all possible mime types, per default only the ones bigger than  20 bytes will be gzipped
        gzip on;
        gzip_types text/plain text/javascript text/css application/json;

        # try to resolve static files (like css or images) if not found (like the url path) return the index.html
        location / {
            try_files $uri $uri/ /index.html;
        }

        location /health {
            access_log off;
            add_header 'Content-Type' 'text/plain';
            return 200 "healthy\n";
        }

        location /api/ {
            proxy_pass http://backend:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /auth/ {
            proxy_pass http://keycloak:8080/;
            proxy_http_version 1.1;
            proxy_set_header HOST $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_cache_bypass $http_upgrade;
        }

        location /auth {
            return 301 /auth/;
        }

        # Block access to admin paths
        # location /auth/admin/ {
        #    return 403;
        # }

        # Block access to the health and metrics endpoints
        # location /auth/health {
        #    return 403;
        # }

        # location /auth/metrics {
        #    return 403;
        # }
    }
}
