FROM quay.io/keycloak/keycloak:26.0 as builder
# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure database vendor
ENV KC_DB=postgres

# Copy realm file
COPY realms/ /opt/keycloak/data/import/

# Add the provider JAR file to the providers directory
ADD --chmod=0666 https://github.com/awslabs/aws-advanced-jdbc-wrapper/releases/download/2.3.1/aws-advanced-jdbc-wrapper-2.3.1.jar /opt/keycloak/providers/aws-advanced-jdbc-wrapper.jar

# Run optimized build
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.0

COPY --from=builder /opt/keycloak/ /opt/keycloak/

# Use non-root user
USER 1000

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

CMD ["start-dev", \
    "--proxy-headers=xforwarded", \
    "--http-relative-path=/auth", \
    "--import-realm" \]
