name: Infrastructure Deployment

on:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/infrastructure.yml"
      - "Makefile"
  pull_request:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/infrastructure.yml"
      - "Makefile"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev/staging/prod)"
        required: true
        default: "dev"

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Install dependencies
        run: make setup

      - name: Preview changes
        if: github.event_name == 'pull_request'
        run: make deploy ENV=${{ github.event.inputs.environment || 'dev' }} -- preview

      - name: Deploy changes
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: make deploy ENV=${{ github.event.inputs.environment || 'dev' }}
